### ISSUE TITLE
upgrade to spring data 2.0

### ISSUE THREAD

**Issue by yungez** [Microsoft/spring-data-documentdb#11]

**Comment by pyryjook** [comment]
Hi! Is there a roadmap for this support?

**Comment by sophiaso** [comment]
@pyryjook A new version [2.0.1](https://mvnrepository.com/artifact/com.microsoft.azure/spring-data-documentdb/2.0.1) has been released. Thanks.

**Comment by sophiaso** [comment]
[Release 2.0.1](https://github.com/Microsoft/spring-data-documentdb/releases/tag/v2.0.1)
