### ISSUE TITLE
Support IndexingPolicy for a collection

### ISSUE THREAD

**Issue by tanhuynh** [Microsoft/spring-data-documentdb#23]
It looks like the current implementation does not allow the client to specify IndexingPolicy for a collection.  It would be great if this can be specified as part of the Document Annotation

**Comment by yungez** [comment]
@tanhuynh  thanks for this feature request. To support IndexingPolicy, we'll need to think over the end to end scenario of indexing, including creating, updating and deleting clearly. currently we're working on plan to support it. will update the issue to once there's more detail.

**Comment by Incarnation-p-lee** [comment]
@tanhuynh  we add the support for indexingPolicy, with new Annotation DocumentIndexingPolicy. Have a try and any issue/problem please feel free to contact us directly.

**Comment by Incarnation-p-lee** [comment]
Done in 2600f859f720c98d7012e656219bf27bba44d6d3
