### ISSUE TITLE
Unable to cast JSONArray to java.util.List

### ISSUE THREAD

**Issue by qlikstar** [Microsoft/spring-data-documentdb#32]
Hi Team,
I am using "com.microsoft.azure:azure-documentdb-spring-boot-starter" in my gradle project.
The data format I am using is :
Document stored in Cosmos is 

 `{
    "id": "1",
    "policyId": 3,
    "deviceId": 2,
    "jobs": [
        "sdy",
        "hjgdjewg"
    ]
}`

I am trying to get this in a POJO. Here is the POJO class.
`@Document(collection = "deviceinfo")
public class DeviceInfo implements Serializable {
    @Id
    private String id;
    private Integer deviceId;
    private Integer policyId;
    private List<String> jobs;
}
`

When I am trying to fetch the data, the spring boot shows the error message : "java.lang.ClassCastException: Cannot cast org.json.JSONArray to java.util.List"

Whereas, if I remove "private List<String> jobs" from my POJO class, it works fine.

Thanks,
Sanket.

**Comment by sophiaso** [comment]
@qlikstar Thanks for the report. Could you share which version of spring-data-documentdb are you using? If it's a released version, could you clone the latest master branch and do a local maven install, and use a snapshot version to test whether the List field works for you?

**Comment by yungez** [comment]
@qlikstar  fix of the issue is merged into master branch already, as @sophiaso mentioned, you could local snapshot version from latest build. or wait for a new version of azure-documentdb-spring-boot-starter. Next release date would be around end of next week.

**Comment by yungez** [comment]
Duplicate of # 22

**Comment by qlikstar** [comment]
Thank you :)
