### ISSUE TITLE
Support null fields in MappingDocumentDbConverter

### ISSUE THREAD

**Issue by rgong1987** [Microsoft/spring-data-documentdb#74]
Hi there,

Is it possible to support null fields in MappingDocumentDbConverter? I can see in JsonSerializable, it will check the null value and store it when does the mapping.

`        if (value == null) {
            this.propertyBag.put(propertyName, JSONObject.NULL);
        }`

So i would expect the same behaviour in MappingDocumentDbConverter? Correct me if I am wrong 😄 

Thanks,
Robbie

**Comment by Incarnation-p-lee** [comment]
@rgong1987 
Actually, the behavior should be the same as JsonSerializable, the MappingDocumentDbConverter will obtain the value of property( of cause it is null). And pass it to Json.

`targetDocument.set(field.getName(), mapToDocumentDBValue(accessor.getProperty(property)))`

For example, if one field is null, we may get null here.

`mapToDocumentDBValue(accessor.getProperty(property)`.

**Comment by rgong1987** [comment]
@Incarnation-p-lee  ah yes, i got it wrong. It is a bit mess with my groovy class which made the property to be null (the above line)

Thanks for your reply!

**Comment by Incarnation-p-lee** [comment]
@rgong1987 
Never mind, and Thank you~

**Comment by rgong1987** [comment]
Hi @Incarnation-p-lee ,

Just out of curiosity, is there any reason you are throwing error when property is  null (by Assertion ) instead of ignoring unknown properties? 

I know this is not designed for groovy, but it really makes me struggle to bypass some groovy default properties... 😞

**Comment by Incarnation-p-lee** [comment]
Hi @rgong1987 
I am not familiar with groovy. But for java in most case, it reflected property(not the property value from accesser) cannot be null here. So we just assume that can hardly happen and use Assertion here. I am not sure this answers your question. Feel free contact us if in problem.
